// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FUCK BDC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <head>
        {/* stops iOS from hiding the composer and removes top jump */}
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, viewport-fit=cover"
        />
        {/* better dark system integration */}
        <meta name="color-scheme" content="dark light" />
        {/* avoid white flash before hydration by setting bg early */}
        <style>{`html,body{background:#0a0a0a;color:#fff}`}</style>
        {/* optional no-FOUC theme guard if you ever persist theme
        <script dangerouslySetInnerHTML={{__html:
          \`try{var t=localStorage.getItem('theme'); if(t==='light'){document.documentElement.classList.remove('dark')} }catch(e){}\`
        }} />
        */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-950 text-white`}
      >
        {children}
      </body>
    </html>
  );
}
